#!/bin/bash
export SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

/usr/bin/nitrogen --restore & 
$HOME/.config/polybar/launch.sh &
# conky -c $HOME/.config/leftwm/themes/custom-theme/conky2.conf -m 3 & 
# echo "LoadTheme $SCRIPTPATH/theme.toml" > $XDG_RUNTIME_DIR/leftwm/commands.pipe
leftwm command "LoadTheme $SCRIPTPATH/theme.toml"
# conky -c $HOME/.config/bspwm/system-overview &
picom --config $HOME/.config/leftwm/themes/custom-theme/picom.conf --experimental &
